version: '3'
services:
  backend:
    build: ./backend
    platform: "linux/arm64"
    volumes:
      - ./backend:/app
      - ./extensions:/app/extensions
      - ./profile:/app/profile
    ports:
      - '4000:4000'

  frontend:
    build: ./frontend
    platform: "linux/arm64"
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    environment:
      - VITE_API_URL=http://localhost:4000
